language: node_js
node_js:
- '12'
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: ql11VXAFeVfMk9LyfLdOSdhNj1KBq99a4TwO4ofLKvqF3b4Bv5DY5A8VFIZYWtz8pF99ilVqFrNLftHQLPxvT4l0P58w4Qda3sOB2iEoEtRWJl4AGGKwKSPrVn1i/UgPpg2NgRBji6LdBlAntFPg1BWtEJOgzWOIBmXeo5uS4tE6xAIrRzJuSEQgRFBj55V8ZSRNyLE3Z9R08N6ldRRYOthKlGbEiNw7+uPpAZUnH/706shbV/w7DS/jfOf6avyl9GhR3VPSugOSVb6L3+IZJzucRzUlvdjQZQ8E8NrXjR6PuZb26Oh75xD7xXH5MrRq74XPwvFo6fYRWceLfCAVyaejQyiZBsAFME//RY86/0UPpjVMsXRT8e6pOwwsKIDJfIG5ySbyosuTV419t/fBIYUYEaFw/Rfp2+PPJ/PVn9xnRDHmXPVmVtrSIAbrEBJ3KwY0f3h7dHnBnaZhkUfwlVG3+BNiNBKu24EboCER7+icCjJK9js9Gx6XhX4MmuWZmBVlU2D7PbTk0m7pjH3/GG7Jws7YPLLZouVOiSdG+Mpnwcl6laW36GGFAFCUhcf8Cnf9swua+rvBkbEJHUBngV0DgdG4h/ricNeNmtqep2oyY3ZlRdvA6cIh44V3sCSN+OGxZ+RxsujzBUvNFqt1zqgU3aRalLfCM0P6qmIa+hU=
